import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      {/* QUI avviene la magia: 
          Diciamo: "Sfondo = Panna (bbro-background)"
          Diciamo: "Testo = Marrone (bbro-foreground)"
      */}
      <body className="antialiased bg-bbro-background text-bbro-foreground">
        {children}
      </body>
    </html>
  );
}